<?php
declare(strict_types=1);
/**
 * Limesharp_Stockists extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category	Limesharp
 * @package		Limesharp_Stockists
 * @copyright	2017 Claudiu Creanga
 * @license		http://opensource.org/licenses/mit-license.php MIT License
 * @author		Claudiu Creanga & David Buxarrais
 */

 /** @var \Limesharp\Stockists\Block\Stockists $block */

$data = $block->getStoresForFrontend();
$countryList = $block->getCountries();
$modulePath = "limesharp_stockists/stockist/image/";
$templateSetting = $block->getTemplateSettings();
$storeDetails = $this->getDetails();
$storeId = $block->getStoreId();
$stockist_id = $storeDetails["stockist_id"];

if ( $block->getMapPin() )
{
	$mapPin = $block->getMediaUrl()."limesharp_stockists/".$block->getMapPin();
}
else
{
	$mapPin = $block->getViewFileUrl('Limesharp_Stockists::images/map_pin.png');
}

?>

<style type="text/css">

span.fa-stack
{
	background-color: #ffd100;
	border-radius: 4px;
	margin-right: .5em;
}

</style>

<div class="row">
	<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 cuadro1-1">
		<div class="image">
			<img src="<?php echo $block->getBaseImageUrl().$modulePath.$block->escapeHtml($storeDetails["details_image"]) ?>"
				 alt="<?php echo $block->escapeHtml(__($storeDetails["address"])) ?>" />
		</div>
		<h4><?php echo $block->escapeHtml(__("Intro")) ?></h4>
		<p>
			<?php echo $block->escapeHtml(__($storeDetails["intro"])); ?>
		</p>
		<h4><?php echo $block->escapeHtml(__("Description")) ?></h4>
		<p>
			<?php echo $block->escapeHtml(__($storeDetails["description"])); ?>
		</p>
	</div>
	<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 cuadro1-1">
		<!-- <h1><?php echo $block->escapeHtml($storeDetails["name"]) ?></h1> -->
		<ul style="padding: 0;">
			<li class="stockists-services">
<?php
				$vehicles = "";

				if ($storeDetails['turismo'] == 1):
					$vehicles .= "turismo";
?>
				<span class="fa-stack fa-lg" style="padding: 0 5px;">
					<img src="<?php echo $block->getViewFileUrl('images/icon-car.svg') ?>">
				</span>
<?php
				endif;

				if ($storeDetails['moto'] == 1):

					if ( !empty($vehicles) )
						$vehicles .= ", ";

					$vehicles .= "moto";
?>
				<span class="fa-stack fa-lg" style="padding: 0 5px;">
					<img src="<?php echo $block->getViewFileUrl('images/icon-moto.svg') ?>">
				</span>
<?php
				endif;

				if ($storeDetails['camion'] == 1):

					if ( !empty($vehicles) )
						$vehicles .= ", ";

					$vehicles .= "camion";
?>
				<span class="fa-stack fa-lg" style="padding: 0 5px;">
					<img src="<?php echo $block->getViewFileUrl('images/icon-truck.svg') ?>">
				</span>
<?php
				endif;

				if ($storeDetails['agricola'] == 1):

					if ( !empty($vehicles) )
						$vehicles .= ", ";

					$vehicles .= "agricola";
?>
				<span class="fa-stack fa-lg" style="padding: 0 5px;">
					<img src="<?php echo $block->getViewFileUrl('images/icon-agro.svg') ?>">
				</span>
<?php
				endif;
?>
			</li>
			<li>
				<i class="fa fa-home" aria-hidden="true"></i> <span><?php echo $block->escapeHtml($storeDetails["address"]) ?></span>
			</li>
			<li>
				<i class="fa fa-globe" aria-hidden="true"></i> <span><?php echo $block->escapeHtml($storeDetails["postcode"] . " " . $block->escapeHtml($storeDetails["city"]) . " (" . $storeDetails["region"]) ?>)</span>
			</li>
			<li>
				<i class="fa fa-phone" aria-hidden="true"></i> <a href="tel:<?php echo $block->escapeHtml($storeDetails["phone"]) ?>"><?php echo $block->escapeHtml($storeDetails["phone"]) ?></a>
			</li>
			<li>
				<i class="fa fa-calendar" aria-hidden="true"></i> <span><?php echo $block->escapeHtml($storeDetails["schedule"]) ?></span>
			</li>
			<li>
				<i class="fa fa-envelope" aria-hidden="true"></i> <a href="mailto:a<?php echo $block->escapeHtml($storeDetails["email"]) ?>" target="_blank"><?php echo $block->escapeHtml($storeDetails["email"]) ?></a>
			</li>
			<li>
				<i class="fa fa-map" aria-hidden="true"></i> <a target="_newtab" href="https://www.google.com/maps/dir//<?php echo $storeDetails['latitude'] . ',' . $storeDetails['longitude'] . '/@' . $storeDetails['latitude'] . ',' . $storeDetails['longitude'] ?>,17z"><?php /* @escapeNotVerified */ echo __('Cómo llegar') ?></a>
			</li>
			<li style="padding: 0; margin-top:25px;">
				<a href="/turismo/presupuesto/presupuesto-neumaticos" class="btn pressu no-ajax_link" style=" width: 100%; background: #ffd100; color: #444649; border: 0; font-weight: bold;"><?php /* @escapeNotVerified */ echo __('Solicitar presupuesto') ?></a>
			</li>
		</ul>
		<div id="map-canvas-individual"></div>
	</div>
</div>

<?php if ( $block->getOtherStoresSettings() ): ?>
	<div class="all-stores">
		<div class="all-stores-title">
			<p><?php echo $block->escapeHtml(__("View Our Other Stores")) ?></p>
		</div>
		<div class="all-stores-slider-wrapper">
			<?php foreach($data as $store): ?>
				<?php $stores = explode(",", $store["store_id"]); ?>
				<?php if (in_array($storeId, $stores) and $storeDetails["stockist_id"] != $store["stockist_id"]): ?>
					<div class="item">
						<div class="image">
							<img src="<?php echo $block->getBaseImageUrl() . $modulePath . $block->escapeHtml($store["image"]) ?>"
								 alt="<?php echo $block->escapeHtml($store["address"]) ?>" />
						</div>
						<a href="<?php echo $block->escapeHtml(__($store["link"])) ?>" class="individual-store-link">
							<div class="details">
								<p><?php echo $block->escapeHtml(__($store["name"])) ?></p>
							</div>
						</a>
					</div>
				<?php endif; ?>
			<?php endforeach; ?>
		</div>
	</div>
<?php endif; ?>

<script type="text/x-magento-init">
	{
		"*" : {

			"stockists_individual_stores" : {
				"map_styles" : "<?php echo $block->getMapStyles() ?>",
				"map_pin" : "<?php echo $mapPin; ?>",
				"slider_arrow" : "<?php echo $block->getViewFileUrl('Limesharp_Stockists::images/slider-arrow.svg'); ?>",
				"geolocation" : <?php echo json_encode($block->getLocationSettings()) ?>,
				"otherStores" : <?php echo json_encode($block->getOtherStoresSettings()) ?>,
				"otherStoresSlider" : <?php echo json_encode($block->getSliderSettings()) ?>,
				"modulePath" : "<?php echo $block->getBaseImageUrl().$modulePath; ?>",
				"zoom_individual" : <?php echo json_encode($block->getZoomIndividualSettings()) ?>,
				"storeDetails" : <?php echo json_encode($storeDetails) ?>,
				"radius" : <?php echo json_encode($block->getRadiusSettings()) ?>,
				"apiKey" : "<?php echo $block->getApiKeySettings(); ?>",
				"unit" : "<?php echo $block->getUnitOfLengthSettings() ?>",
				"fillColor" : "<?php echo $block->getFillColorSettings() ?>",
				"fillOpacity" : <?php echo json_encode($block->getFillOpacitySettings()) ?>,
				"strokeColor" : "<?php echo $block->getStrokeColorSettings() ?>",
				"strokeOpacity" : <?php echo json_encode($block->getStrokeOpacitySettings()) ?>,
				"strokeWeight" : <?php echo json_encode($block->getStrokeWeightSettings()) ?>
			}

		}
	}
</script>
