<?php
declare(strict_types=1);
/**
 * Limesharp_Stockists extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category	Limesharp
 * @package		Limesharp_Stockists
 * @copyright	2017 Claudiu Creanga
 * @license		http://opensource.org/licenses/mit-license.php MIT License
 * @author		Claudiu Creanga & David Buxarrais
 */
?>

<?php /** @var \Limesharp\Stockists\Block\Stockists $block */?>

<?php

$_store				= $block->getCurrentStore();
$modulePath			= "limesharp_stockists/stockist/image/";
$templateSetting	= $block->getTemplateSettings();
$storeId			= $block->getStoreId();

if ( $block->getMapPin() )
	$mapPin = $block->getMediaUrl()."limesharp_stockists/".$block->getMapPin();
else
	$mapPin = $block->getViewFileUrl('Limesharp_Stockists::images/map_pin.png');
?>
<!-- there are 4 templates, page_width_top, full_width_top, full_width_sidebar or page_width_sidebar -->
<div class="parent-stockists <?php echo $templateSetting; ?>">
	<div class="search-stockists">
		<div class="search-header">
			<div class="row">
				<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
					<input id="stockist-search-term" type="search" placeholder="CP, Ciudad" autocomplete="off" />
					<button id="stockists-submit"><i class="fa fa-map-marker"></i></button>
<?php
					if ($templateSetting == "page_width_top" or $templateSetting == "full_width_top"):
?>
						<button class="find-my-location"><i class="fa fa-dot-circle-o" aria-hidden="true"></i><!-- <i class="fa fa-compass" aria-hidden="true"></i> --></button>
<?php
					endif;
?>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 text-right">
					<!-- <a href="#ampliar-mapa" class="ampliar-mapa" data-text="Ampliar mapa">Reducir mapa</a> -->
				</div>
			</div>
		</div>
<?php
		if ($templateSetting == "page_width_top" or $templateSetting == "full_width_top"):
?>
	</div>
<?php
	if ($templateSetting == "full_width_top"):
?>
	<div id="map-canvas" style="height: 100%; width: 100%;"></div>
<?php
	endif;
endif;
?>
	<div class="content-stockists">
		<div class="row">
			<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
				<div class="stockists-info">
					<ul class="navbar-vehicle-type">
						<li class="active">
							<input type="hidden" id="type-turismo" name="turismo" value="1">
							<a href="/centros-rodi/turismo">
								<span class="fa fa-check-square fa-2x"></span><?php /* @escapeNotVerified */ echo __('Turismo') ?>
							</a>
						</li>
						<li>
							<input type="hidden" id="type-moto" name="moto" value="0">
							<a href="/centros-rodi/moto">
								<span class="fa fa-square fa-2x"></span><?php /* @escapeNotVerified */ echo __('Moto') ?>
							</a>
						</li>
						<li>
							<input type="hidden" id="type-camion" name="camion" value="0">
							<a href="/centros-rodi/camion">
								<span class="fa fa-square fa-2x"></span><?php /* @escapeNotVerified */ echo __('Camión') ?>
							</a>
						</li>
						<li>
							<input type="hidden" id="type-agricola" name="agricola" value="0">
							<a href="/centros-rodi/agricola">
								<span class="fa fa-square fa-2x"></span><?php /* @escapeNotVerified */ echo __('Agrícola') ?>
							</a>
						</li>
					</ul>
					<label>
						<input type="checkbox" id="renting" name="renting" value="0"> <?php /* @escapeNotVerified */ echo __('Renting') ?>
					</label>
					<label><?php /* @escapeNotVerified */ echo __('Província') ?></label>
					<ul class="navbar-province"></ul>
					<label class="hidden"><?php /* @escapeNotVerified */ echo __('Població') ?></label>
					<ul class="navbar-city"></ul>
					<label class="hidden"><?php /* @escapeNotVerified */ echo __('Centros mas cercanos') ?></label>
					<div class="stockists-results">
						<ul class="navbar-center results-store"></ul>
					</div>
				</div>
			</div>
			<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
				<div class="stockists-window"></div>

				<div class="directions-panel">
					<p><?php /* @escapeNotVerified */ echo __("Your directions"); ?>: </p>
					<p class="change-directions">Change to <span class="walking get-directions" data-directions="WALKING">walking, </span><span class="cycle get-directions" data-directions="BICYCLING">cycling</span>, <span class="transit get-directions" data-directions="TRANSIT">public transport</span> or <span class="driving get-directions" data-directions="DRIVING">driving</span>.</p>
					<div class="close"></div>
				</div>
			</div>
<?php
			if ($templateSetting == "page_width_top"):
?>
			<div id="map-canvas" style="height: 100%; width: 100%;"></div>
<?php
			endif;
?>
		</div>
	</div>
<?php
	if ($templateSetting == "full_width_sidebar" or $templateSetting == "page_width_sidebar"):
?>
	</div>
<?php
	endif;
?>
</div>

<?php if ($templateSetting == "full_width_sidebar" or $templateSetting == "page_width_sidebar"): ?>
<div id="map-canvas" style="height: 100%; width: 100%;"></div>
<?php endif; ?>

<script type="text/x-magento-init">
{
	"*":
	{
		"limesharp_stockists":
		{
			"moduleUrl"		: "<?php echo $block->getModuleUrlSettings(); ?>"
		,	"map_styles"	: "<?php echo $block->getMapStyles(); ?>"
		,	"map_pin"		: "<?php echo $mapPin; ?>"
		,	"geolocation"	: <?php echo json_encode($block->getLocationSettings()); ?>
		,	"zoom"			: <?php echo json_encode($block->getZoomSettings()); ?>
		,	"latitude"		: <?php echo json_encode($block->getLatitudeSettings()); ?>
		,	"longitude"		: <?php echo json_encode($block->getLongitudeSettings()); ?>
		,	"radius"		: <?php echo json_encode($block->getRadiusSettings()); ?>
		,	"template"		: "<?php echo $templateSetting; ?>"
		,	"apiKey"		: "<?php echo $block->getApiKeySettings(); ?>"
		,	"unit"			: "<?php echo $block->getUnitOfLengthSettings(); ?>"
		,	"fillColor"		: "<?php echo $block->getFillColorSettings(); ?>"
		,	"fillOpacity"	: <?php echo json_encode($block->getFillOpacitySettings()); ?>
		,	"strokeColor"	: "<?php echo $block->getStrokeColorSettings(); ?>"
		,	"strokeOpacity"	: <?php echo json_encode($block->getStrokeOpacitySettings()); ?>
		,	"strokeWeight"	: <?php echo json_encode($block->getStrokeWeightSettings()); ?>
		,	"images"		: {
								"turismo"	: "<?php echo $block->getViewFileUrl('images/icon-car.svg') ?>"
							,	"moto"		: "<?php echo $block->getViewFileUrl('images/icon-moto.svg') ?>"
							,	"camion"	: "<?php echo $block->getViewFileUrl('images/icon-truck.svg') ?>"
							,	"agricola"	: "<?php echo $block->getViewFileUrl('images/icon-agro.svg') ?>"
							}
		}
	}
}
</script>
